### ISSUE TITLE
Using non-INAV font with INAV OSD causes a error 

### ISSUE THREAD

**Issue by kirek007** [kirek007/ws-osd-py#17]
Stack trace:
```
DEBUG:root:File drop: C:\Users\wilco\Downloads\pre-release-88c19ba942ba0af66e779dd71e07674a244e1d40-windows\release\user_bf_24.png
DEBUG:root:Preview update requested.
Traceback (most recent call last):
  File "osd_gui.py", line 32, in OnDropFiles
  File "pubsub\core\publisher.py", line 216, in sendMessage
  File "pubsub\core\topicobj.py", line 452, in publish
  File "pubsub\core\topicobj.py", line 482, in sendMessage
  File "pubsub\core\listener.py", line 237, in call
  File "osd_gui.py", line 379, in eventConfigUpdate
  File "osd_gui.py", line 383, in onView
  File "processor.py", line 396, in generate_preview
  File "processor.py", line 396, in <listcomp>
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix_operations.cpp:67: error: (-215:Assertion failed) src[i].dims <= 2 && src[i].rows == src[0].rows && src[i].type() == src[0].type() in function 'cv::hconcat'

Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "processor.py", line 624, in main
  File "processor.py", line 523, in render_osd_frame
  File "processor.py", line 523, in <listcomp>
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix_operations.cpp:67: error: (-215:Assertion failed) src[i].dims <= 2 && src[i].rows == src[0].rows && src[i].type() == src[0].type() in function 'cv::hconcat'
```

**Comment by kirek007** [comment]
It should be better now, but to be tested.
