### ISSUE TITLE
Software fails to generate images with SRT option unchecked

### ISSUE THREAD

**Issue by WereWolfPL** [kirek007/ws-osd-py#25]
Latest pre-release: https://github.com/kirek007/ws-osd-py/releases/tag/master-f9342f2523c7bf0e6a5d4871e4be7d01a2a1f6d2

Errors in the console:

```
Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "processor.py", line 648, in main
UnboundLocalError: local variable 'frame_osd_srt' referenced before assignment
```

**Comment by kirek007** [comment]
Right, will be fixed soon (TM)

**Comment by WereWolfPL** [comment]
Looks like it's fixed in the latest beta.
