### ISSUE TITLE
help me : Why am I getting this error?, Is there any workaround?

### ISSUE THREAD

**Issue by jsungho** [kirek007/ws-osd-py#54]
Same error in all versions.
This is the text that appears in the command window below.
Moving other fonts gives the same error.

------------------------------------------------

DEBUG:root:File drop: E:\ㅇ Downloade\release\AvatarG0059.mp4
DEBUG:root:File drop: E:\ㅇ Downloade\release\user_ardu_36.png
[ WARN:0@16.588] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('E:\?Traceback (most recent call last):
  File "osd_gui.py", line 32, in OnDropFiles
  File "pubsub\core\publisher.py", line 216, in sendMessage
  File "pubsub\core\topicobj.py", line 452, in publish
  File "pubsub\core\topicobj.py", line 482, in __sendMessage
  File "pubsub\core\listener.py", line 237, in __call__
  File "osd_gui.py", line 103, in eventConfigUpdate
  File "osd_gui.py", line 114, in updateSettings
  File "osd_gui.py", line 123, in updateInfo
  File "processor.py", line 70, in is_hd
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by jsungho** [comment]
Moving it to another folder works fine. thank you.
Folders with special characters not working
